name: mcjolt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - tqdm>=4.62.0
  - statsmodels>=0.13.0
  - pyarrow>=6.0.0
  - jupyter>=1.0.0
  - pip>=21.0.0
  - pip:
    - torch>=1.10.0
